# Tokenization Testing

### Testing Tokenizer Values

In [1]:
# Model Names: 
# 'bert-base-uncased' (bert)
# 'bert-base-multilingual-cased' (mBERT)
# 'xlm-roberta-base' or "distilroberta-base" (XLM-RoBERTa, Distil Roberta)
# "google-bert/bert-base-cased" (mobileBert)

MODEL_NAME = 'xlm-roberta-base'

In [29]:
text = "Cheers to a new year, Scott! Start 2024 with a bang as a Smart Postpaid subscriber! Reap your rewards with a P5,000 Welcome Gift from UnionBank when you apply for their UnionBank Rewards Credit Card and set up Auto Bills Payment for your Postpaid Account. But that's not all - say GOODBYE to Annual Fees FOREVER! Just spend P20,000 within 60 days of approval. Apply now! smrt.ph/UBWelcomeGift Promo runs until Feb. 29, 2024. T&Cs apply. DTI#181104"

In [4]:
MAX_LENGTH = 150

In [5]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
# model = TFAutoModelForSequenceClassification.from_pretrained(
#     MODEL_NAME,
#     num_labels=2,
#     # hidden_dropout_prob=0.3,
#     # attention_probs_dropout_prob=0.15
# )

In [41]:
# prepare input
encoded_input = tokenizer(
    text, 
    max_length=MAX_LENGTH,
    truncation=True,
    return_tensors='tf'
)

# forward pass
# output = model(**encoded_input)

# print(encoded_input)

In [42]:
num_tokens = encoded_input["input_ids"].shape[1]
print(f"Number of tokens: {num_tokens}")

Number of tokens: 8


In [43]:
decoded_text = tokenizer.decode(encoded_input["input_ids"].numpy()[0], skip_special_tokens=True)
print("--- tokenized text object value:")
print(encoded_input)
print("\n")
print("--- decoded text from tokenized data:") 
print(decoded_text)
print("--- real text:")
print(text)

--- tokenized text object value:
{'input_ids': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=
array([[    0, 47801,   929,   823,  8699, 41267,   408,     2]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


--- decoded text from tokenized data:
Nickol Jairo Belgica
--- real text:
Nickol Jairo Belgica


### Show token number > text

In [65]:
text = "bagay"

In [66]:
from transformers import RobertaTokenizer

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Sample text
# text = "This is an example sentence for RoBERTa tokenization."

# Tokenize the text and get token IDs
tokens = tokenizer.tokenize(text)
token_ids = tokenizer.convert_tokens_to_ids(tokens)

# Format each token with its respective token ID
formatted_tokens = "\n".join(f"{token_id} > {token}" for token_id, token in zip(token_ids, tokens))

# Print the result
print(formatted_tokens)

58316 > ▁bagay
